services:
   # fragments:
   # build: ./
   # ports:
   # - "8080:8080"
   # # env_file: ./.env
   # restart: always
   # environment:
   # - NODE_ENV=production
   # - PRODUCTION=false
   # - HTPASSWD_FILE=./tests/.htpasswd
   # network_mode: "host"

   fragments:
      image: shawnyu5/fragments:latest
      init: true
      ports:
         - "8080:8080"
      env_file: ./.env
      environment:
         - NODE_ENV=production
         - PRODUCTION=false
         - HTPASSWD_FILE=./tests/.htpasswd
      # network_mode: "host"
