services:
   fragments:
      build: .
      init: true
      environment:
         # Our API will be running on http://localhost:8080
         - API_URL=http://localhost:8080
         # Use Basic Auth (for running tests, CI)
         - HTPASSWD_FILE=tests/.htpasswd
         # Use the LOG_LEVEL set in the host environment, or default to info
         - LOG_LEVEL=${LOG_LEVEL:-info}
         - PRODUCTION=false
         - AWS_S3_BUCKET_NAME=hyu126-fragments
         - AWS_DYNAMODB_TABLE_NAME=fragments
      # Ports to publish
      ports:
         - "8080:8080"

      # DynamoDB Local, see: https://hub.docker.com/r/amazon/dynamodb-local
   dynamodb-local:
      image: amazon/dynamodb-local
      ports:
         # Default port is 8000
         - "8000:8000"
      # Run the database in memory, see:
      # https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html
      command: ["-jar", "DynamoDBLocal.jar", "-inMemory"]

      # LocalStack for S3, see https://docs.localstack.cloud/get-started/#docker-compose
      # Interact via awscli-local, see https://docs.localstack.cloud/integrations/aws-cli/#installation
   localstack:
      # https://hub.docker.com/r/localstack/localstack
      image: localstack/localstack
      ports:
         - "4566:4566"
      environment:
         # See https://docs.localstack.cloud/localstack/configuration/ and
         # https://hub.docker.com/r/localstack/localstack for config details.
         # We only want to run S3
         - SERVICES=s3
         # We're always working in us-east-1
         - DEFAULT_REGION=us-east-1
